### ISSUE TITLE
Cloud Storage Provider Request - Mega

### ISSUE THREAD

**Issue by redxtech** [buttercup/dossier#1]
Is it reasonable to request that you add mega to the list of potential cloud storage integrations? I'm not 100% sure how the API relates to that of some other providers, but it's built with privacy and end-to-end encryption in mind, so I personally think that it would be a good idea.

**Comment by perry-mitchell** [comment]
Thanks @redxtech - Not sure on the popularity of Mega, so I'd prefer to personally see some feedback from others before deciding if we'll include this. Either than or some usage statistics of the platform (number of users, geos, etc.)..

**Comment by perry-mitchell** [comment]
Since this has been somewhat quiet, I'll close the issue. We'd prefer to discuss viable storage vendors in a more casual manner for now, as integration is a lot of work. You can either raise a discussion on it via our [reddit comm.](https://www.reddit.com/r/bcup/) or via [Keybase](https://keybase.io/team/bcup).
